/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopsNearYouRouteImport } from './routes/shops-near-you'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlatesRouteImport } from './routes/plates'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as ChatThreadIdRouteImport } from './routes/chat.$threadId'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiWhoIcdSearchRouteImport } from './routes/api/who-icd/search'
import { Route as ApiRxnormSearchRouteImport } from './routes/api/rxnorm/search'
import { Route as ApiOpenfdaSearchRouteImport } from './routes/api/openfda/search'
import { Route as ApiNutritionSearchRouteImport } from './routes/api/nutrition/search'
import { Route as ApiEdamamImageFoodRouteImport } from './routes/api/edamam/image-food'

const ShopsNearYouRoute = ShopsNearYouRouteImport.update({
  id: '/shops-near-you',
  path: '/shops-near-you',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatesRoute = PlatesRouteImport.update({
  id: '/plates',
  path: '/plates',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhoIcdSearchRoute = ApiWhoIcdSearchRouteImport.update({
  id: '/api/who-icd/search',
  path: '/api/who-icd/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRxnormSearchRoute = ApiRxnormSearchRouteImport.update({
  id: '/api/rxnorm/search',
  path: '/api/rxnorm/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenfdaSearchRoute = ApiOpenfdaSearchRouteImport.update({
  id: '/api/openfda/search',
  path: '/api/openfda/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNutritionSearchRoute = ApiNutritionSearchRouteImport.update({
  id: '/api/nutrition/search',
  path: '/api/nutrition/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEdamamImageFoodRoute = ApiEdamamImageFoodRouteImport.update({
  id: '/api/edamam/image-food',
  path: '/api/edamam/image-food',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/plates': typeof PlatesRoute
  '/profile': typeof ProfileRoute
  '/report': typeof ReportRoute
  '/shops-near-you': typeof ShopsNearYouRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/chat/': typeof ChatIndexRoute
  '/api/edamam/image-food': typeof ApiEdamamImageFoodRoute
  '/api/nutrition/search': typeof ApiNutritionSearchRoute
  '/api/openfda/search': typeof ApiOpenfdaSearchRoute
  '/api/rxnorm/search': typeof ApiRxnormSearchRoute
  '/api/who-icd/search': typeof ApiWhoIcdSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/plates': typeof PlatesRoute
  '/profile': typeof ProfileRoute
  '/report': typeof ReportRoute
  '/shops-near-you': typeof ShopsNearYouRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/chat': typeof ChatIndexRoute
  '/api/edamam/image-food': typeof ApiEdamamImageFoodRoute
  '/api/nutrition/search': typeof ApiNutritionSearchRoute
  '/api/openfda/search': typeof ApiOpenfdaSearchRoute
  '/api/rxnorm/search': typeof ApiRxnormSearchRoute
  '/api/who-icd/search': typeof ApiWhoIcdSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/plates': typeof PlatesRoute
  '/profile': typeof ProfileRoute
  '/report': typeof ReportRoute
  '/shops-near-you': typeof ShopsNearYouRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/chat/': typeof ChatIndexRoute
  '/api/edamam/image-food': typeof ApiEdamamImageFoodRoute
  '/api/nutrition/search': typeof ApiNutritionSearchRoute
  '/api/openfda/search': typeof ApiOpenfdaSearchRoute
  '/api/rxnorm/search': typeof ApiRxnormSearchRoute
  '/api/who-icd/search': typeof ApiWhoIcdSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/dashboard'
    | '/docs'
    | '/login'
    | '/onboarding'
    | '/plan'
    | '/plates'
    | '/profile'
    | '/report'
    | '/shops-near-you'
    | '/api/chat'
    | '/chat/$threadId'
    | '/chat/'
    | '/api/edamam/image-food'
    | '/api/nutrition/search'
    | '/api/openfda/search'
    | '/api/rxnorm/search'
    | '/api/who-icd/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/docs'
    | '/login'
    | '/onboarding'
    | '/plan'
    | '/plates'
    | '/profile'
    | '/report'
    | '/shops-near-you'
    | '/api/chat'
    | '/chat/$threadId'
    | '/chat'
    | '/api/edamam/image-food'
    | '/api/nutrition/search'
    | '/api/openfda/search'
    | '/api/rxnorm/search'
    | '/api/who-icd/search'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/dashboard'
    | '/docs'
    | '/login'
    | '/onboarding'
    | '/plan'
    | '/plates'
    | '/profile'
    | '/report'
    | '/shops-near-you'
    | '/api/chat'
    | '/chat/$threadId'
    | '/chat/'
    | '/api/edamam/image-food'
    | '/api/nutrition/search'
    | '/api/openfda/search'
    | '/api/rxnorm/search'
    | '/api/who-icd/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PlanRoute: typeof PlanRoute
  PlatesRoute: typeof PlatesRoute
  ProfileRoute: typeof ProfileRoute
  ReportRoute: typeof ReportRoute
  ShopsNearYouRoute: typeof ShopsNearYouRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiEdamamImageFoodRoute: typeof ApiEdamamImageFoodRoute
  ApiNutritionSearchRoute: typeof ApiNutritionSearchRoute
  ApiOpenfdaSearchRoute: typeof ApiOpenfdaSearchRoute
  ApiRxnormSearchRoute: typeof ApiRxnormSearchRoute
  ApiWhoIcdSearchRoute: typeof ApiWhoIcdSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shops-near-you': {
      id: '/shops-near-you'
      path: '/shops-near-you'
      fullPath: '/shops-near-you'
      preLoaderRoute: typeof ShopsNearYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plates': {
      id: '/plates'
      path: '/plates'
      fullPath: '/plates'
      preLoaderRoute: typeof PlatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/chat/$threadId': {
      id: '/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/who-icd/search': {
      id: '/api/who-icd/search'
      path: '/api/who-icd/search'
      fullPath: '/api/who-icd/search'
      preLoaderRoute: typeof ApiWhoIcdSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rxnorm/search': {
      id: '/api/rxnorm/search'
      path: '/api/rxnorm/search'
      fullPath: '/api/rxnorm/search'
      preLoaderRoute: typeof ApiRxnormSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openfda/search': {
      id: '/api/openfda/search'
      path: '/api/openfda/search'
      fullPath: '/api/openfda/search'
      preLoaderRoute: typeof ApiOpenfdaSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nutrition/search': {
      id: '/api/nutrition/search'
      path: '/api/nutrition/search'
      fullPath: '/api/nutrition/search'
      preLoaderRoute: typeof ApiNutritionSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/edamam/image-food': {
      id: '/api/edamam/image-food'
      path: '/api/edamam/image-food'
      fullPath: '/api/edamam/image-food'
      preLoaderRoute: typeof ApiEdamamImageFoodRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PlanRoute: PlanRoute,
  PlatesRoute: PlatesRoute,
  ProfileRoute: ProfileRoute,
  ReportRoute: ReportRoute,
  ShopsNearYouRoute: ShopsNearYouRoute,
  ApiChatRoute: ApiChatRoute,
  ApiEdamamImageFoodRoute: ApiEdamamImageFoodRoute,
  ApiNutritionSearchRoute: ApiNutritionSearchRoute,
  ApiOpenfdaSearchRoute: ApiOpenfdaSearchRoute,
  ApiRxnormSearchRoute: ApiRxnormSearchRoute,
  ApiWhoIcdSearchRoute: ApiWhoIcdSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
